Repository atomvm/AtomVM, pull requests merged in 2023-08, with the labels that each got.

#718 SPI: fix `mode` that wasn't working
  doc/src/programmers-guide.md
  src/platforms/esp32/components/avm_builtins/spi_driver.c
Labels: bug, peripherals

#703 generic_unix: exports symbols in order to make plugins work
  src/platforms/generic_unix/CMakeLists.txt
Labels: blocking

#618 Add enif_select support to esp32
  src/libAtomVM/erl_nif.h
  src/platforms/esp32/components/avm_sys/CMakeLists.txt
  src/platforms/esp32/components/avm_sys/include/esp32_sys.h
  src/platforms/esp32/components/avm_sys/sys.c
  src/platforms/esp32/test/main/test_erl_sources/CMakeLists.txt
  src/platforms/esp32/test/main/test_erl_sources/test_select.erl
  src/platforms/esp32/test/main/test_main.c
Labels: blocking

#687 Added interop_iolist_fold
  src/libAtomVM/interop.c
  src/libAtomVM/interop.h
Labels: blocking

#740 ESP32/SPI: informative errors
  libs/eavmlib/src/spi.erl
  src/platforms/esp32/components/avm_builtins/spi_driver.c
Labels: platform:esp32, peripherals, blocking

#741 ESP32/NVS: return tagged tuples instead of just the result
  CHANGELOG.md
  doc/src/network-programming-guide.md
  libs/eavmlib/src/esp.erl
  src/platforms/esp32/components/avm_builtins/nvs_nif.c
Labels: platform:esp32, blocking

#753 ESP32/NVS: fix typos and other smaller issues
  libs/eavmlib/src/esp.erl
  src/platforms/esp32/components/avm_builtins/nvs_nif.c
Labels: bug
